site_traffic/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('traffic.urls') ),
]

traffic/urls.py
from django.urls import path,include
from . import views
app_name = 'traffic'
urlpatterns = [
   
    # path('',views.home, name ='home' ),
    path ('', views.test_form, name="index"),
    # path('',views.home, name ='home' ),
    # path('',views.site_traffic, name ='site_traffic' ),


]

traffic/models.py
from django.db import models

# Create your models here.

traffic/forms.py
from django import forms

class SiteUrl(forms.Form):
    site_url = forms.CharField(max_length=100)

traffic/views.py
from django.db.models.expressions import Value
from django.db.models.lookups import Contains
from django.http import response
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
import requests
from requests.api import request
from .forms import SiteUrl

# Create your views here.


# def test_form(request):
#     if request.method == "POST":
#         mssg = 'site not found'
#         site = request.POST.get("site_url")
#         print({"site": site})
#         return render(
#                 request,
#                 "page_data.html",
#                 {
#                     "site": site,
#                     'error':mssg})

#     else:
#         return render(request,'index.html')


def test_form(request):
    if request.method == "POST":

        site = request.POST.get("site_url")
        print({"site": site})

        form = SiteUrl(request.POST)

        #     site = 'www.google.com'

        url = "https://similarweb2.p.rapidapi.com/pageoverview"

        querystring = {"website": "https://" + site}

        headers = {
            "x-rapidapi-host": "similarweb2.p.rapidapi.com",
            "x-rapidapi-key": "23a1830e2amshb300f3a2bac9a56p1793d1jsn2b8cb9b48d12",
        }
        # ##########This gets the data from the api
        response = requests.request("GET", url, headers=headers, params=querystring)
        # test_response = requests.request("GET",'https://' + site)

        if response.status_code == 200:
            print("works")
        else:
            mssg = 'Input a website with the format "www.example.com"'
            return render(request, "index.html",{'error':mssg})


        ####Convert the api response to json
        context = response.json()
        # from the json data, we get whatever data we need
        description = context["siteDescription"]
        rank = context["categoryRank"]["rank"]
        screenshot = context["pageScreenshot"]
        print(response.text)

        ######Here, we render the data to the html template
        return render(
            request,
            "page_data.html",
            {
                "site": site,
                # 'response':context,
                "" "rank": rank,
                "description": description,
                "screenshot": screenshot,
            },
        )
    
  

    else:
        mssg = 'Input a website with the format "www.example.com"'
        return render(request, "index.html",{'error':mssg})



###################REGEX

# if site Contains a schema, no need to add schema else add https:// to the url
# for example, app.netlify.test should work if the site is valid...
# if it diwsnt work we have an error page sha....To create new page or nah...think......

# import re
# regex = “((http|https)://)(.)?” + “[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]” + “{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)”
# website = re.search(r'((http|https)://)')

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
<link rel="stylesheet" type="text/css" href=" {% static '/css/style.css' %}"> 
<title>Site Info</title>
</head>
<body>
    <div class="main">
    <h1>
        Know This Website
         </h1>

        <p>This website gives you relevant information on any website in the world</p>
        
<div class="form">
        <form method="POST" action="{% url 'traffic:index' %}">
            {% csrf_token %}
            <input type="text" name="site_url" placeholder="URL example = www.example.com">
            <input class="btn" type="submit" name="submit">
        </form></div>
        <h2>{{mssg}}</h2>
        {% block content %}
        {% endblock content %}
    
    </div>
</body>
</html>

templates/page_data.html
{% extends 'index.html' %}


{% block content %}



<h3>{{site}}</h3>
        <h4>Rank: {{rank}}</h4>
<h4>Description: {{description}}</h4>
<h4>screenshot:<img src="{{screenshot}}" alt="">  </h4>
<a href="{{screenshot}}">Full screen</a>




{% endblock content %}